version: '3.7'

services:
  db:
    container_name: "bitgin_db"
    image: mysql:8.0.23
    platform: linux/x86_64
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    container_name: "bitgin_phpmyadmin"
    image: phpmyadmin/phpmyadmin
    ports:
      - "8888:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

  api:
    container_name:  "bitgin_api"
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./src:/app/

networks:
  default:
volumes:
  mysql_data: