package model

const (
	USERROLE_NORMAL        = "N"
	USERROLE_VIP1          = "V1"
	USERROLE_VIP2          = "V2"
	USERROLE_VIP3          = "V3"
	USERROLE_NOR_DISCOUNT  = 1
	USERROLE_VIP1_DISCOUNT = 0.95
	USERROLE_VIP2_DISCOUNT = 0.9
	USERROLE_VIP3_DISCOUNT = 0.85
)
